# name: "Hello Actions" #cosmetic
# description: "Greet someone" #cosmetic
# author: "octocat@github.com" #cosmetic

inputs:
  MY_NAME:
    # description: "Who to greet" 
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"