### DOCKER

# name: A workflow for my Hello World file
# on: push

# jobs:
#   build:
#     # name: Hello world action
#     runs-on: ubuntu-latest #specifying the operating system that the underlying vm is running on
#     steps:
#       - uses: actions/checkout@v1 
#       - uses: ./action-a
#         with:
#           MY_NAME: "Mona"


### JAVASCRIPT

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: natkozak/hello-github-actions
      # - uses: ./action-a #copied from above to see if I can keep the action.yml where it is
        with:
          who-to-greet: 'Nat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"